#!/bin/bash

cat <<EOF > init.sql
CREATE DATABASE IF NOT EXISTS test_${MYSQL_DATABASE};
GRANT ALL PRIVILEGES ON test_${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'%' IDENTIFIED BY 'mypassword';
FLUSH PRIVILEGES;
EOF