# Generated by Django 5.0.6 on 2024-06-04 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='reference_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='address_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.address'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.address'),
        ),
    ]
